#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Command\GreetCommand;

$application = new Application();
$application->add(new \Command\MembersAcceptCommand());
$application->add(new \Command\ImportMembersCommand());
$application->add(new \Command\ImportProjectsCommand());
$application->add(new \Command\XferMembersCommand());
//$application->add(new \Command\XferDataCommand());
$application->add(new \Command\ExampleCommand());
$application->add(new \Command\SummaryWavesCommand());
$application->add(new \Command\SummaryTasksCommand());
$application->add(new \Command\SummaryProjectsCommand());
$application->add(new \Command\SummaryMembersCommand());
$application->add(new \Command\SummaryUsersCommand());
$application->add(new \Command\SummaryImagesCommand());
$application->run();