#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Command\GreetCommand;

$application = new Application();
$application->add(new \Command\ExternalWeatherCommand());
$application->add(new \Command\MembersAcceptCommand());
$application->add(new \Command\MembersImportCommand());
$application->add(new \Command\ProjectsImportCommand());
//$application->add(new \Command\XferDataCommand());
$application->add(new \Command\ExampleCommand());
$application->add(new \Command\WavesSummaryCommand());
$application->add(new \Command\WavesXferCommand());
$application->add(new \Command\SurveysXferCommand());
$application->add(new \Command\TasksSummaryCommand());
$application->add(new \Command\ProjectsListCommand());
$application->add(new \Command\MemberSummaryCommand());
$application->add(new \Command\UsersSummaryCommand());
$application->add(new \Command\ImagesSummaryCommand());
$application->add(new \Command\TrackingIntervalCommand());
$application->add(new \Command\TrackTasksCommand());
$application->add(new \Command\UsersDailySummaryCommand());
$application->add(new \Command\XferMembersCommand());
$application->add(new \Command\XferLocationsCommand());
$application->add(new \Command\XferDataCommand());
$application->add(new \Command\ExportDataCommand());
$application->run();
